# Generated by Django 3.2.6 on 2021-08-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chapter_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chapter_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('chapter_desc', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
