# Generated by Django 3.2.6 on 2021-08-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('only_maths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='yt_link',
            field=models.URLField(default='https://www.youtube.com/c/AnjeshNITJ', max_length=150),
        ),
    ]
