# Generated by Django 3.2.6 on 2021-09-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('only_maths', '0002_chapter_yt_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('contact_desc', models.CharField(max_length=1000)),
            ],
        ),
    ]
