# Generated by Django 3.2.6 on 2021-11-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('only_maths', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('main_heading', models.CharField(max_length=50)),
                ('sub_heading', models.CharField(max_length=50)),
                ('first_link', models.URLField(default='https://www.youtube.com/c/AnjeshNITJ', max_length=150)),
                ('second_link', models.URLField(default='https://www.youtube.com/c/AnjeshNITJ', max_length=150)),
            ],
        ),
    ]
